# language: node_js
# node_js: v8.9.0
# notifications:
#   slack: 
#     rooms:
#       - compileio:uAKGKPc1MCWywPZsmgrWGFrb
#     on_success: change
#     on_failure: always

deploy:
language: java
cache:
  directories:
    - Frontend/compile-io-frontend-app/node_modules
before_install:
  - npm i -g npm@latest
script:
  - cd Spring_Server/gs-uploading-files-complete && ./gradlew test
  - ./gradlew bootRun -Dspring.profiles.active=prod`
  # - ./gradlew build
  - java -jar build/libs/gs-spring-boot-0.1.0.jar
  - cd ../../Frontend/compile-io-frontend-app
  - ng build --prod
  - ng serve --prod

notifications:
  slack: 
    rooms:
      - compileio:uAKGKPc1MCWywPZsmgrWGFrb
    on_success: change
    on_failure: always
  
